name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["React CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "Install Vercel CLI"
        run: npm install -g vercel

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: "Deploy to Vercel"
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --name react-cicd